"OSError: [Errno 17] File exists" when trying to use os.makedirs [duplicate]
